### ISSUE TITLE
Replace all SBHQ linka with Imagulation 

### ISSUE THREAD

**Issue by AnmolPlayzz** [AnmolPlayzz/AnmolPlayzz.github.io#10]
SB was discontinued
so I need to change all links

- [x] Home page
- [x] Contact Page
- [x] Socials Page

**Comment by TheEpicDragons** [comment]
@AnmolPlayzz you should close this issue now.

**Comment by AnmolPlayzz** [comment]
No
need to update the images

**Comment by TheEpicDragons** [comment]
Then do it, it's almost been a month from when this issue had been opened

**Comment by AnmolPlayzz** [comment]
Done.
